org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true

nows_version=0.4.0
minecraft_version=26.2
nows_release_base_url=https://files.nows.space/releases/nows

geb_core_version=0.5.4
geb_processor_version=0.4.9
netty_version=4.2.15.Final
kdl4j_version=1.0.1
reactor_version=3.8.6
disruptor_version=4.0.0
mixin_version=0.8.7
datafixerupper_version=10.0.21
brigadier_version=1.3.10
